services:
  - type: web
    name: sentinel-core
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GROQ_API_KEY
        sync: false

      # 🔥 THIS IS THE FIX
      - key: COQUI_TOS_AGREED
        value: "1"
